import { TProps as TPropertyCards } from "@/components";

import { PropertyCardImage } from "../../../../public";

export const PROPERTY_CARDS: TPropertyCards[] = [
    {
        image: PropertyCardImage.property_1,
        address: "709 West Drive Chicago, IL 60606",
        price: 3500,
        title: "Comefortable Appartment",
        buttonLink: "/",
        beds: 3,
        baths: 2,
        parking: 1,
        square: 120,
    },
    {
        image: PropertyCardImage.property_2,
        address: "709 West Drive Chicago, IL 60606",
        price: 3500,
        title: "Home in Downtown, Los Angeles",
        buttonLink: "/",
        beds: 3,
        baths: 2,
        parking: 1,
        square: 120,
    },
    {
        image: PropertyCardImage.property_3,
        address: "709 West Drive Chicago, IL 60606",
        price: 3500,
        title: "Comefortable Appartment",
        buttonLink: "/",
        beds: 3,
        baths: 2,
        parking: 1,
        square: 120,
    },
    {
        image: PropertyCardImage.property_4,
        address: "709 West Drive Chicago, IL 60606",
        price: 3500,
        title: "Home in Downtown, Los Angeles",
        buttonLink: "/",
        beds: 3,
        baths: 2,
        parking: 1,
        square: 120,
    },
    {
        image: PropertyCardImage.property_5,
        address: "709 West Drive Chicago, IL 60606",
        price: 3500,
        title: "Comefortable Appartment",
        buttonLink: "/",
        beds: 3,
        baths: 2,
        parking: 1,
        square: 120,
    },
    {
        image: PropertyCardImage.property_6,
        address: "709 West Drive Chicago, IL 60606",
        price: 3500,
        title: "Home in Downtown, Los Angeles",
        buttonLink: "/",
        beds: 3,
        baths: 2,
        parking: 1,
        square: 120,
    },
];
