import { TPropertyCards } from "@/components";
import { PROPERTY_CARD_IMG } from "@public";

export const PROPERTY_CARDS: TPropertyCards[] = [
    {
        image: PROPERTY_CARD_IMG.property_1,
        address: "709 West Drive Chicago, IL 60606",
        price: 3500,
        title: "Comefortable Appartment",
        buttonLink: "/",
        beds: 3,
        baths: 2,
        parking: 1,
        square: 120,
    },
    {
        image: PROPERTY_CARD_IMG.property_2,
        address: "709 West Drive Chicago, IL 60606",
        price: 3500,
        title: "Home in Downtown, Los Angeles",
        buttonLink: "/",
        beds: 3,
        baths: 2,
        parking: 1,
        square: 120,
    },
    {
        image: PROPERTY_CARD_IMG.property_3,
        address: "709 West Drive Chicago, IL 60606",
        price: 3500,
        title: "Comefortable Appartment",
        buttonLink: "/",
        beds: 3,
        baths: 2,
        parking: 1,
        square: 120,
    },
    {
        image: PROPERTY_CARD_IMG.property_4,
        address: "709 West Drive Chicago, IL 60606",
        price: 3500,
        title: "Home in Downtown, Los Angeles",
        buttonLink: "/",
        beds: 3,
        baths: 2,
        parking: 1,
        square: 120,
    },
    {
        image: PROPERTY_CARD_IMG.property_5,
        address: "709 West Drive Chicago, IL 60606",
        price: 3500,
        title: "Comefortable Appartment",
        buttonLink: "/",
        beds: 3,
        baths: 2,
        parking: 1,
        square: 120,
    },
    {
        image: PROPERTY_CARD_IMG.property_6,
        address: "709 West Drive Chicago, IL 60606",
        price: 3500,
        title: "Home in Downtown, Los Angeles",
        buttonLink: "/",
        beds: 3,
        baths: 2,
        parking: 1,
        square: 120,
    },
];
